[package]
authors = ["Joslin, Brady W (Brady) <brady@bradyjoslin.com>"]
edition = "2018"
name = "rsieve"
version = "0.0.6"

[dependencies]
assert_cmd = "1.0.8"
flate2 = "1.0.9"
openssl = { version = "0.10.32", optional = true, features = ["vendored"] }
reqwest = "0.11.3"
run_script = "0.7.0"
structopt = "0.3"
tar = "0.4.26"
tokio = {version = "1.5", features = ["full"]}
regex = "1.4.5"
glob = "0.3.0"
ptree = "0.3.2"
home = "0.5.3"
console = "0.14.1"
git2 = "0.13.17"

[dev-dependencies]
assert_cmd = "1.0.8"
predicates = "1"

[features]
default = ['openssl/vendored']