[package]
authors = ["Joslin, Brady W (Brady) <brady@bradyjoslin.com>"]
edition = "2018"
name = "rsieve"
version = "0.0.6"

[dependencies]
assert_cmd = "2.0.0"
flate2 = "1.0.9"
openssl = { version = "0.10.35", optional = true, features = ["vendored"] }
reqwest = "0.11.4"
run_script = "0.8.0"
structopt = "0.3"
tar = "0.4.37"
tokio = {version = "1.10", features = ["full"]}
regex = "1.5.4"
glob = "0.3.0"
ptree = "0.3.2"
home = "0.5.3"
console = "0.14.1"
git2 = "0.13.17"

[dev-dependencies]
assert_cmd = "2.0.0"
predicates = "2"

[features]
default = ['openssl/vendored']