[package]
authors = ["Joslin, Brady W (Brady) <brady@bradyjoslin.com>"]
edition = "2018"
name = "rsieve"
version = "0.0.7"

[dependencies]
assert_cmd = "2.0.4"
flate2 = "1.0.22"
openssl = { version = "0.10.40", optional = true, features = ["vendored"] }
reqwest = "0.11.8"
run_script = "0.9.0"
structopt = "0.3"
tar = "0.4.38"
tokio = {version = "1.16", features = ["full"]}
regex = "1.5.5"
glob = "0.3.0"
ptree = "0.4.0"
home = "0.5.3"
console = "0.15.0"
git2 = "0.13.25"

[dev-dependencies]
assert_cmd = "2.0.4"
predicates = "2"

[features]
default = ['openssl/vendored']