[package]
authors = ["Joslin, Brady W (Brady) <brady@bradyjoslin.com>"]
edition = "2018"
name = "rsieve"
version = "0.0.7"

[dependencies]
assert_cmd = "2.0.1"
flate2 = "1.0.22"
openssl = { version = "0.10.36", optional = true, features = ["vendored"] }
reqwest = "0.11.5"
run_script = "0.9.0"
structopt = "0.3"
tar = "0.4.37"
tokio = {version = "1.12", features = ["full"]}
regex = "1.5.4"
glob = "0.3.0"
ptree = "0.3.2"
home = "0.5.3"
console = "0.14.1"
git2 = "0.13.23"

[dev-dependencies]
assert_cmd = "2.0.1"
predicates = "2"

[features]
default = ['openssl/vendored']