name: Test

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable

      - name: Run Unit Tests
        run: cargo test --bins -- --skip gets_github_git_repos

      - name: Run Integration Tests
        run: cargo test --test integration -- --test-threads=1