name: Test

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable

      - name: Run Tests
        run: cargo test -- --skip gets_github_git_repos